title: "Taaha's Website"
author: "Taaha Kazi"
description: "NLP Intern at Samsung Research America (SRA) | Masters in Computer Science at University of Illinois Urbana-Champaign | NLP | ML"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:tnkazi2@illinois.edu"}
  - {title: Github, icon: github, url: "https://github.com/TaahaKazi/"}
  - {title: Linkedin, icon: fa-brands fa-linkedin , url: "https://www.linkedin.com/in/taahakazi/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
